#!/usr/bin/python3

import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=3:
    print("All inputs are correct")
    sys.exit()

Main_Server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

Main_Server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)



Command = (sys.argv[1])
c=Command.split(':')
ip_address=str(c[0])
port=int(c[1])
nick=str(sys.argv[2])


Main_Server.connect((ip_address, port))

Message1=Main_Server.recv(2048).decode('utf-8')

print(Message1)

nick = 'NICK ' + nick


Main_Server.sendall(nick.encode('utf-8'))

Reply=Main_Server.recv(2048).decode('utf-8')
print(Reply)
if Reply == "OK":
    pass
elif Reply == "Oops! Err nick name":
    print('Disconnecting')
    sys.exit()
    
    



while True:
    socket_list=[sys.stdin, Main_Server]
    

    read_sockets,write_sockets,error_sockets=select.select(socket_list,[],[])
    
    for sockets in read_sockets:
        if sockets == Main_Server:
            info = sockets.recv(2048).decode('utf-8')
            print(info)
        else:
            info=sys.stdin.readline()
            
            info = 'message_from '+ info
            if info == '\n':
                continue
            else:
                Main_Server.sendall(info.encode('utf-8'))
                
Main_Server.close()

